# Generated by Django 3.2 on 2023-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name*')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject*')),
                ('message', models.TextField(verbose_name='Message*')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Subscribe to newsletter')),
                ('sent_date', models.DateField(auto_now_add=True, verbose_name='Sent Date')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
